package edu.sjsu.teamneon.hangrymobile;

import android.os.Parcel;
import android.os.Parcelable;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.*;

import java.util.List;
import java.util.Map;


/**
 * Created by danieltam on 3/11/17.
 * Truck mapper class
 */

@DynamoDBTable(tableName = "Trucks")
public class FoodTruck implements Parcelable {
    private String id; //Google account's ID
    private String name; //Truck name
    private String lon;
    private String lat;
    private Integer isTruck; //Truck owner or customer
    private String description;
    private Map<String, Map<String, String>> menu;
    private Map<String, Integer> rating;

//    public FoodTruck(String name, String lon, String lat) {
//        super();
//        this.name = name;
//        this.lon = lon;
//        this.lat = lat;
//    }

    public FoodTruck() {
        super();
    }

    private FoodTruck(Parcel in){
        this.id = in.readString();
        this.name = in.readString();
        this.lon = in.readString();
        this.lat = in.readString();
    }

    public static final Parcelable.Creator<FoodTruck> CREATOR =
        new Parcelable.Creator<FoodTruck>() {

        @Override
        public FoodTruck createFromParcel(Parcel source) {
            return new FoodTruck(source);
        }

        @Override
        public FoodTruck[] newArray(int size) {
            return new FoodTruck[size];
        }
    };

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getID() {
        return id;
    }

    public void setID(String id) {
        this.id = id;
    }

    @DynamoDBIndexRangeKey(attributeName = "name")
    public String getName(){
        return name;
    }

    public void setName(String name){
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "lon")
    public String getLon() {
        return lon;
    }

    public void setLon(String lon) {
        this.lon = lon;
    }

    @DynamoDBAttribute(attributeName = "lat")
    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    @DynamoDBAttribute(attributeName = "isTruck")
    public Integer getIsTruck(){
        return isTruck;
    }

    public void setIsTruck(Integer isTruck){
        this.isTruck = isTruck;
    }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription(){
        return description;
    }

    public void setDescription(String description){
        this.description = description;
    }

    @DynamoDBAttribute(attributeName = "Menu")
    public Map<String, Map<String, String>> getMenu(){
        return menu;
    }

    public void setMenu(Map<String, Map<String, String>> menu){
        this.menu = menu;
    }

    @DynamoDBAttribute(attributeName = "rating")
    public Map<String, Integer> getRating(){
        return rating;
    }

    public void setRating(Map<String, Integer> rating){
        this.rating = rating;
    }



    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(id);
        dest.writeString(name);
        dest.writeString(lon);
        dest.writeString(lat);
    }
}